# @package model
_target_: model.architecture.diffusion_model.DiffusionModel
d_model: 128
num_heads: 4
num_layers: 5
d_ff: 256
max_seq_length: 128
dropout: 0.1
vocab_size: null  # Will be computed automatically

# Configurable metrics - diffusion model focuses on path-specific metrics  
enabled_metrics:
  - accuracy
  - path_validity
  - edge_accuracy
  - path_optimality
