# @package model
_target_: model.architecture.iterative_conv.IterativeConvModel
d_model: 128
num_iterations: 6
kernel_size: 3
num_layers: 4
dropout: 0.1
vocab_size: null  # Will be computed automatically

# Configurable metrics
enabled_metrics:
  - accuracy
  - exact_match_accuracy
  - path_validity

enabled_gen_metrics:
  - gen_path_validity
  - gen_avg_path_length_diff
