# @package model
_target_: model.architecture.past.PAST
d_model: 128
num_heads: 4
num_layers: 8
d_ff: 256
max_seq_length: 128
dropout: 0.1
vocab_size: null  # Will be computed automatically
train_mode: "absorbing"

# Configurable metrics
enabled_metrics:
  - accuracy
  - exact_match_accuracy
  - path_validity
  - edge_accuracy
  - path_optimality
