# @package _global_

# Dataset size sweep configuration (basic sweeper - no Optuna)
# Tests training with different numbers of training samples
# Usage: python train.py +sweeps=dataset_size_sweep --multirun

# Hydra sweep configuration
hydra:
  
  sweep:
    
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}_dataset_size
    subdir: ${hydra.job.num}_samples_${data.num_train_samples}
  sweeper:
    params:
      data.percentage_of_train_samples: 0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0

# Override default config if needed
data:
  num_train_samples: null  # Will be overridden by sweep

training:
  max_epochs: -1  # Adjust as needed
logging:
  experiment_name: dataset_size_sweep