defaults:
  - model: diffusion_upsample
  - training: default
  - data: watts_strogatz
  - _self_
  #- override hydra/sweeper: basic

data_generation:
  train:
    num_paths: 50000
    min_length: 3
    max_length: 36
    # Perturbed path generation settings
    use_perturbed: true  # Set to true to use perturbed shortest paths instead of random walks
    n_segments_min: 2     # Minimum number of segments to split shortest path
    n_segments_max: 10     # Maximum number of segments to split shortest path  
    perturbation_min: 0   # Minimum perturbation steps
    perturbation_max: 0 # Maximum perturbation steps
    unique_pairs_ratio: 0.8  # Ratio of unique pairs to total training paths (e.g., 0.1 means 10% unique pairs)
  test:
    num_paths: 2000
  output_dir: "temp/"

curriculum_learning:
  enabled: false
  min_accuracy_threshold: 0.5  # Accuracy threshold for shortest paths
  max_accuracy_threshold: 0.7  # Accuracy threshold for longest paths
  max_epochs_per_length: 200   # Maximum epochs per length before moving on
  patience: 40                 # Early stopping patience for each length
  # Accuracy thresholds for intermediate lengths will be linearly interpolated

data:
  train_file: "train.json"
  test_file: "test.json"
  max_path_length: 33
  num_workers: 16
  percentage_of_train_samples: 0.9  # Set to a number to limit training samples (null = use all)
  num_val_samples: 2000    # Set to a number to limit validation samples (null = use all)
  

logging:
  project_name: "path_prediction"
  experiment_name: "PathPrediction"
  log_every_n_steps: 50

paths:
  data_dir: "./temp"
  model_dir: "./model"
  checkpoint_dir: "./checkpoints"

# # Optuna sweeper configuration
# hydra:
#   sweeper:
#     # sampler:
#     #   _target_: optuna.samplers.TPESampler
#     #   seed: 123
#     #   n_startup_trials: 1000 
#     params:
#       training.learning_rate: 1e-3
#       #training.loss: "prob_weighting"
#     #direction: minimize
#     # study_name: path_prediction_optimization
#     # storage: null
#     # n_trials: 3
#     # n_jobs: 1